### ISSUE TITLE
Default options for creating links

### ISSUE THREAD

**Issue by Gandalf-the-Blue** [JGeek00/linkdy#12]
Hi,

I'd like to request a feature of setting default tags & default mark as unread toggle option when I share a link to the application to store it. I use an "uncategorized" tag, which I can then manage later on.

**Comment by JGeek00** [comment]
The "mark as unread" toggle already exists, but I can add an option on settings to have a set of tags added by default.

**Comment by JGeek00** [comment]
Added on v1.4.0.
