### ISSUE TITLE
Invalid URL for .foundation domain

### ISSUE THREAD

**Issue by SkipTam** [JGeek00/linkdy#19]
Hi,
I just found a bug where saving URLs that end in .foundation (https://e.foundation/) give back an Invalid URL error and grays out "validate URL" Button.

Device: Apple iPhone 12
IOS Version. 17.5.1
App Version. 1.4.0

If you need more information, im happy to help

**Comment by JGeek00** [comment]
Ok I see that I have to change the regular expression that validates the URLs

**Comment by JGeek00** [comment]
Fixed on v1.5.0.
