### ISSUE TITLE
Unable to connect to linkding instance with additional path in URL

### ISSUE THREAD

**Issue by christianhans** [JGeek00/linkdy#2]
If the linkding instance is running on

```
subdomain.domain.tld/path
```

the presence of `/path` is preventing the connect button from being enabled.

**Comment by JGeek00** [comment]
On my other apps I have a path field on the connection form, but I decided to remove it for this one because I though that no one used it. I will add it on the next release.

**Comment by JGeek00** [comment]
Added on v0.4.0.
