### ISSUE TITLE
Linkdy doesn't function properly with cloudflare

### ISSUE THREAD

**Issue by vaskokj** [JGeek00/linkdy#24]
I have a server that I can add the URL to, it tests properly and seems to login properly with the Linkdink API key that it generated in my account, however, when Linkdy tries to load the website, it fails with "Cannot load the bookmarks", but the app acts like it is logged in successfully.

**Comment by JGeek00** [comment]
I also have my Linking instance behind Cloudflare and for me it works fine. If the app says that it's because cannot reach the server. When the login is completed, the app won't request you to login again. It will only request you to login again if any HTTP response throws a 403 status code.
