### ISSUE TITLE
Can't verify URLs

### ISSUE THREAD

**Issue by swonky** [JGeek00/linkdy#3]
Hi, just wanted to start off by saying great job! Your app looks great so far.

Unfortunately, on my phone I'm unable to add bookmarks. When I tap "Validate URL", I get an error message reading "The URL could not be checked". Without validating the URL, I'm unable to populate the title and description textboxes and add the bookmark.

I'm running version 1.1.0 from the Google Play store. My phone is an ASUS Zenfone 9 running Android 13. 

![Screenshot_20240308-162201](https://github.com/JGeek00/linkdy/assets/80737736/e82c3c5e-61de-4c9a-8698-551c3346b315)

**Comment by JGeek00** [comment]
That's weird. I have inputted the same url on my device and I can validate the URL without any problem.

**Comment by swonky** [comment]
Mine doesn't work with any URL. I may be able to do some more in-depth debugging later in the week. 

In the event that this issue affects more users than just myself, can I suggest that you enable the textboxes so that users can manually add the title and description if the validation fails? That would prevent the app from becoming totally unusable

**Comment by swonky** [comment]
Yes that works fine
![Screenshot_20240311-091832_Firefox (1)](https://github.com/JGeek00/linkdy/assets/80737736/88321e63-085a-4c30-87bc-ec4d0f609eb6)

It also displays as valid if I add the bookmark using the web app, and then edit it using Linkdy (but not if I change the URL afterwards).
![Screenshot_20240311-092045 (1)](https://github.com/JGeek00/linkdy/assets/80737736/ae3c6e63-d7a7-4c88-ada3-1c9fc2ef4dab)

**Comment by swonky** [comment]
I've done a bit more investigation and it doesn't look like its actually an issue with your app. The API request fails, but I also can't seem to get the bookmarks/check API endpoint working with postman either so it seems to be either a linkding issue or something wrong with my instance. I also realise now that you are forced to do the validation via the server and can't simply enable the textboxes.

Sorry for the false alarm. Good luck with your app. Hopefully I can work out what's gone wrong so that I can use it one day.
