### ISSUE TITLE
[Feature request] Target for share menu

### ISSUE THREAD

**Issue by dakush** [JGeek00/linkdy#4]
First of all, great app and thank you for making it!

I see that a new bookmark can be created from within the app, I wonder if it could be possible to also make the app a target of the "Share" menu so we can create new bookmarks just by sharing a URL from other apps. Thanks again!

**Comment by rbtzn** [comment]
Hello, 

I agree :) Great app, Nice job !
It would be a great addition to the app and much simpler to share links with the ability to have the Linkfy app to the Share with menu 

Thanks in advance

**Comment by JGeek00** [comment]
That feature was already on the roadmap :-)

**Comment by JGeek00** [comment]
Added on v1.2.0.
