### ISSUE TITLE
[Feature Request] Auto validate the URL when adding a bookmark from the share menu

### ISSUE THREAD

**Issue by rbtzn** [JGeek00/linkdy#6]
Hello,

Thank you for your work on the latest version !
It could be nice if the URL was auto validated when the user add a bookmark from the share menu

![image](https://github.com/JGeek00/linkdy/assets/164404597/87e1e888-c895-4648-a2b2-06d7ad6f2bb4)

Many thanks !

**Comment by JGeek00** [comment]
Added on v1.2.1.
